apiVersion: apps/v1
kind: Deployment
metadata:
  name: golden-hour
spec:
  template:
    spec:
      containers:
        - name: golden-hour
          imagePullPolicy: Always
          image: registry.digitalocean.com/unmanaged-registry/golden-hour:latest
          ports:
            - containerPort: 8080
  replicas: 1

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  name: golden-hour
spec:
  rules:
    - host: golden-hour.josephfinlayson.com
      http:
        paths:
         - path: /
           backend:
              service: 
                name: golden-hour
                port: 
                  number: 8005      
           pathType: Prefix
  tls:
  - hosts:
      - golden-hour.josephfinlayson.com
    secretName: letsencrypt-production
---
apiVersion: v1
kind: Service
metadata:
  name: golden-hour
spec:
  ports:
    - name: http
      port: 8005
      targetPort: 8080
  selector:
    app: golden-hour-service
  type: NodePort
